/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.mp.client;

import com.sun.javafx.tk.TKSceneListener;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.awt.desktop.AppForegroundListener;
import java.io.*;
import java.net.Socket;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;



public class Client extends Application {

    public static ArrayList<ClientSk> ClientSkList;

    public static void main(String[] args) throws IOException, ClassNotFoundException {
        ClientSkList = new ArrayList<>();
        Application.launch();
    }

    @Override
    public void start(Stage stage) throws Exception {
        game_start();
        stage.setScene(get_scene("Register.fxml"));
        stage.setResizable(true);
        stage.show();
    }

    public void game_start() throws IOException, ClassNotFoundException {
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));

        //System.out.println("Please enter the server host name");
        //String hostName = input.readLine();
        //System.out.println("Please enter the server port number");
        //String port = input.readLine();
        ClientSk clientSk = new ClientSk("0.0.0.0", "9999", input, System.out);
        ClientSkList.add(clientSk);
        new_game("0.0.0.0", "9999", input, System.out);
    }

    public static void new_game(String hostName, String port,
                                BufferedReader input, PrintStream out) throws IOException, ClassNotFoundException {
        if (ClientSkList.size() != 1) {
            ClientSk clientSk = new ClientSk(hostName, port, input, out);
            ClientSkList.add(clientSk);
            ClientSkList.get(ClientSkList.size() - 1).game_begin();
        }
        else {
            ClientSkList.get(0).game_begin();
        }
    }

    public static Scene get_scene(String fileName) throws IOException {
        if (fileName.equals("Login.fxml")){
            return createScene("Login.fxml");
        } else if (fileName.equals("Register.fxml")) {
            return createScene("Register.fxml");
        } else if (fileName.equals("Map2.fxml")) {
            return createScene("Map2.fxml");
        } else if (fileName.equals("Map3.fxml")) {
            return createScene("Map3.fxml");
        }
        else if (fileName.equals("Map4.fxml")) {
            return createScene("Map4.fxml");
        }
        else if (fileName.equals("Map5.fxml")) {
            return createScene("Map5.fxml");
        } else {
            return  null;
        }
    }

    public static Scene createScene(String fileName) throws IOException {
        URL fxmlResource = Client.class.getResource("/ui/" + fileName);
        FXMLLoader loader = new FXMLLoader(fxmlResource);
        VBox vbox = loader.load();
        Scene scene = new Scene(vbox, 1920, 1080);
        return scene;
    }
}
