/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.mp.client;

import java.io.IOException;

public class Client {
    public static void main(String[] args) throws IOException, ClassNotFoundException {
        ClientSk clientSk = new ClientSk();
        clientSk.accept_map();
        System.out.println();
    }


}
