/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.mp.server;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class ServerTest {

}
