/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.mp.server;

import edu.duke.ece651.mp.common.*;

import java.io.IOException;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.HashSet;

public class Server {

    public static void main(String[] args) throws IOException {
        String filename = "Territory.txt";
        int numPlayer = 3;
        Parse parse = new Parse();
        HashSet<Territory> result = parse.parseTerritoryNeighbor(filename, numPlayer);
        GameMap gm = new BasicMap("Map 1", parse.parseColor("Color.txt", numPlayer), result);
        gm.assign_all();
        ArrayList<GameMap> maps = new ArrayList<>();
        maps.add(gm);
        ServerSk serverSk = new ServerSk(maps);
        serverSk.build_server();
    }
}
