/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.mp.server;

import edu.duke.ece651.mp.common.*;

import java.io.IOException;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.HashSet;

public class Server {

    public static void main(String[] args) throws IOException {
        ArrayList<GameMap> maps = new ArrayList<>();
        Server server = new Server();
        GameMap gm = server.create_one_map("Territory2.txt", 2);
        maps.add(gm);
        ServerSk serverSk = new ServerSk(maps, 9999);
        serverSk.build_server();
    }

    /**
     *
     * @param filename used to parse to generate a map
     * @param numPlayer
     * @return the generated game map
     * @throws IOException
     */
    public GameMap create_one_map(String filename, int numPlayer) throws IOException {
        Parse parse = new Parse();
        HashSet<Territory> result = parse.parseTerritoryNeighbor(filename, numPlayer);
        GameMap gm = new BasicMap("Map 1", parse.parseColor("Color.txt", numPlayer), result);
        gm.assign_all();
        gm.init_num_units();
        return gm;
    }
}
